# Generated by Django 3.2.4 on 2021-06-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='slug_content',
            new_name='blog_content',
        ),
    ]
